export const labsInfo = [
  {
    labName: 'Vinod Menon Lab Name',
    labDescription: 'Vinod Menon Lab Description.\n Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate soluta eum ratione voluptates minima consequuntur odio totam incidunt, earum quo? Rerum, debitis? Quasi sapiente iure explicabo soluta non molestias laboriosam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique laborum, praesentium sequi aliquam assumenda rerum! Repellendus nisi asperiores animi molestias necessitatibus ex commodi! Dolor nulla quo maxime nobis ducimus cum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maxime id nobis deleniti ipsam facere, recusandae eum aut doloribus velit minus, qui sapiente esse! Eligendi rem ex suscipit veniam eveniet! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore corporis eos aspernatur, deleniti sint delectus voluptate laudantium necessitatibus repellat. Ullam dolorem ab rerum! Magnam eligendi obcaecati optio perferendis laborum. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate quibusdam ab ex, quo unde possimus magni sint! Fugiat molestiae cum exercitationem sunt harum vel voluptatibus asperiores nam, quod, recusandae ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum praesentium officia sit est esse dolorum, totam impedit qui. Eum cumque fugit deserunt iste! Ipsa, pariatur praesentium. Laboriosam, maxime et? Cum! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime saepe dolorem, minima, sit rem placeat quae optio iusto quibusdam, tenetur consequuntur suscipit velit explicabo? Commodi amet culpa velit hic laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam fuga nostrum laboriosam ipsa inventore quis iste, facere sapiente rerum harum ipsum eum, nam possimus error omnis quos architecto delectus quaerat! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo distinctio iusto sit odio earum ratione corporis eveniet dolorum. Dolor recusandae reprehenderit autem et tempora molestias incidunt in? Ratione, commodi tempora. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laboriosam rerum dolore, dolorum explicabo perspiciatis corrupti! Reiciendis, placeat molestias fugit deserunt cumque sunt ratione asperiores suscipit laborum saepe aperiam. Animi, obcaecati. kiren.',
    bgPng: './img/menon-lab-cover.png',
    bgWebp: './img/menon-lab-cover.webp'
  },
  {
    labName: 'Andrea Blanco-Redondo Lab Name',
    labDescription: 'Andrea Blanco-Redondo Lab Description. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate soluta eum ratione voluptates minima consequuntur odio totam incidunt, earum quo? Rerum, debitis? Quasi sapiente iure explicabo soluta non molestias laboriosam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos fugiat iure nemo, maiores qui laudantium odit tenetur repellendus esse voluptates nam. Fuga ullam aliquam aperiam reiciendis laboriosam ea, maxime obcaecati. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Unde aliquid consequatur rem ratione. Corporis doloribus amet, vel tempore dolorem earum fugiat ea ratione laborum, sunt accusantium nihil dolor, neque odio? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Praesentium non quibusdam consequuntur at exercitationem minus nihil consectetur, repellendus expedita vitae animi ut harum autem voluptatum, delectus velit qui voluptatem dolore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique laborum, praesentium sequi aliquam assumenda rerum! Repellendus nisi asperiores animi molestias necessitatibus ex commodi! Dolor nulla quo maxime nobis ducimus cum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maxime id nobis deleniti ipsam facere, recusandae eum aut doloribus velit minus, qui sapiente esse! Eligendi rem ex suscipit veniam eveniet! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore corporis eos aspernatur, deleniti sint delectus voluptate laudantium necessitatibus repellat. Ullam dolorem ab rerum! Magnam eligendi obcaecati optio perferendis laborum. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate quibusdam ab ex, quo unde possimus magni sint! Fugiat molestiae cum exercitationem sunt harum vel voluptatibus asperiores nam, quod, recusandae ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum praesentium officia sit est esse dolorum, totam impedit qui. Eum cumque fugit deserunt iste! Ipsa, pariatur praesentium. Laboriosam, maxime et? Cum! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime saepe dolorem, minima, sit rem placeat quae optio iusto quibusdam, tenetur consequuntur suscipit velit explicabo? Commodi amet culpa velit hic laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam fuga nostrum laboriosam ipsa inventore quis iste, facere sapiente rerum harum ipsum eum, nam possimus error omnis quos architecto delectus quaerat!',
    bgPng: './img/redondo-lab-cover.png',
    bgWebp: './img/redondo-lab-cover.webp'
  },
  {
    labName: 'Carlos Meriles Lab Name',
    labDescription: 'Carlos Meriles Lab Description. Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ipsa officia enim in voluptatibus eos expedita debitis consequuntur architecto nulla aspernatur perferendis, tenetur esse iusto quod sint officiis ab quibusdam! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab quam incidunt totam minus magnam, maxime eligendi sapiente aliquam. Praesentium, corporis explicabo? Aperiam harum voluptas quasi rerum. Commodi saepe recusandae totam?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt quos facilis odio delectus corporis quis et a illum ea amet rem cupiditate officia fuga, nostrum inventore, assumenda beatae vitae veritatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique qui, perspiciatis rerum praesentium nemo officia cupiditate facere at consectetur aliquid assumenda voluptatem vero laboriosam. Beatae voluptatem quisquam commodi optio nisi. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corporis ex, mollitia optio saepe praesentium eaque magnam veniam dolor necessitatibus nihil. Commodi itaque vel fugiat dolore quis corporis eveniet repellat at. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque minima nostrum incidunt odit ad quibusdam rem deserunt corrupti delectus numquam veniam, mollitia est non explicabo inventore at harum unde. Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ex facilis repudiandae excepturi adipisci doloremque natus voluptates aliquam, mollitia laborum tempore dolorum inventore earum eligendi reprehenderit possimus recusandae? Quae, in. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, tenetur consequatur. Nobis, quo! Aut, nam! Nemo, porro est! Temporibus quis veniam eos unde esse enim repellat. Nostrum temporibus minima dolorum? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim possimus voluptas repudiandae error sunt nisi placeat, neque fugiat, omnis odit reprehenderit odio accusamus culpa voluptatem a beatae natus ipsa. Maxime? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit perferendis sint fugit alias nulla? Quod numquam commodi est blanditiis earum laborum at, doloribus aperiam qui repellat fugiat placeat odit reprehenderit. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo voluptatem at similique, consequatur voluptatum animi a fugiat, consectetur, non temporibus laborum nemo? Pariatur nihil, expedita totam dicta unde delectus eius. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam impedit fuga perspiciatis repellat, doloribus voluptatem error cum optio vitae tenetur modi sequi ratione reprehenderit id culpa praesentium repudiandae minima eum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facere cum tenetur inventore nesciunt sunt accusantium labore, optio deserunt distinctio corrupti adipisci voluptate, iste, pariatur minima sit autem reiciendis dolorem nulla!',
    bgPng: './img/meriles-lab-cover.png',
    bgWebp: './img/meriles-lab-cover.webp'
  },
  {
    labName: 'Roger Dorsinville Lab Name',
    labDescription: 'Roger Dorsinville Lab Description. Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, voluptatum consectetur, quasi asperiores iure magni expedita laboriosam iste dolorem velit beatae laudantium? Impedit doloribus eaque nostrum ea porro qui placeat? Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae nesciunt autem quos debitis eius consequuntur temporibus aspernatur quam, qui facere praesentium. Sit ducimus repellat perspiciatis ipsam praesentium beatae esse eius. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Est, officiis cum ipsam adipisci animi illo laboriosam quisquam. Corporis dolores nulla dolor. Repudiandae nihil dicta vitae atque ducimus illum perspiciatis dolore. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Est minima accusantium laborum delectus facilis saepe consectetur deserunt, similique quibusdam incidunt sit, odit cumque quas! Ratione sit magni perspiciatis vel dolorem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum id ad modi ex, quasi minus voluptate quam mollitia harum doloribus itaque. Labore consequuntur nisi reiciendis suscipit unde, quidem dignissimos! Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate officiis aspernatur voluptates, nobis cum adipisci rem culpa modi, iusto et aperiam voluptate? Impedit perferendis distinctio nihil dolore ex iure neque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea repellendus in dolore ad voluptas aperiam asperiores, nesciunt nisi dignissimos deserunt placeat architecto id reprehenderit modi quaerat voluptates velit distinctio eius. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reprehenderit neque aspernatur, quasi pariatur laboriosam dolore eveniet facere ipsam rem at deleniti non illum repellat consequatur? Ipsam dolorum et sequi ducimus. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe, quaerat animi sunt provident hic dignissimos accusamus quae iure ullam. Officia cum, saepe obcaecati eaque vero quas perspiciatis deserunt eum nobis. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis omnis quos fuga alias totam consectetur sequi deserunt quod laboriosam, necessitatibus perferendis magni corporis vitae impedit voluptate consequuntur praesentium ad suscipit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam atque nulla minus ipsum, unde architecto quod laborum et suscipit? Esse magni dolore ipsum sapiente fugiat atque sequi iusto, beatae nulla?',
    bgPng: './img/dorsinville-lab-cover.png',
    bgWebp: './img/dorsinville-lab-cover.webp'
  },
  {
    labName: 'Alexander Khanikaev Lab Name',
    labDescription: 'Alexander Khanikaev Lab Description. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate soluta eum ratione voluptates minima consequuntur odio totam incidunt, earum quo? Rerum, debitis? Quasi sapiente iure explicabo soluta non molestias laboriosam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique laborum, praesentium sequi aliquam assumenda rerum! Repellendus nisi asperiores animi molestias necessitatibus ex commodi! Dolor nulla quo maxime nobis ducimus cum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maxime id nobis deleniti ipsam facere, recusandae eum aut doloribus velit minus, qui sapiente esse! Eligendi rem ex suscipit veniam eveniet! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore corporis eos aspernatur, deleniti sint delectus voluptate laudantium necessitatibus repellat. Ullam dolorem ab rerum! Magnam eligendi obcaecati optio perferendis laborum. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate quibusdam ab ex, quo unde possimus magni sint! Fugiat molestiae cum exercitationem sunt harum vel voluptatibus asperiores nam, quod, recusandae ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum praesentium officia sit est esse dolorum, totam impedit qui. Eum cumque fugit deserunt iste! Ipsa, pariatur praesentium. Laboriosam, maxime et? Cum! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime saepe dolorem, minima, sit rem placeat quae optio iusto quibusdam, tenetur consequuntur suscipit velit explicabo? Commodi amet culpa velit hic laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam fuga nostrum laboriosam ipsa inventore quis iste, facere sapiente rerum harum ipsum eum, nam possimus error omnis quos architecto delectus quaerat! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo distinctio iusto sit odio earum ratione corporis eveniet dolorum. Dolor recusandae reprehenderit autem et tempora molestias incidunt in? Ratione, commodi tempora. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laboriosam rerum dolore, dolorum explicabo perspiciatis corrupti! Reiciendis, placeat molestias fugit deserunt cumque sunt ratione asperiores suscipit laborum saepe aperiam. Animi, obcaecati. kiren',
    bgPng: './img/khanikaev-lab-cover.png',
    bgWebp: './img/khanikaev-lab-cover.webp',
  }
]